# Generated by Django 4.0 on 2022-04-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='Language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
