# Generated by Django 4.0 on 2022-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authorname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
