# Generated by Django 4.0 on 2022-02-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
