# Generated by Django 4.0 on 2022-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_language_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
