# Generated by Django 4.0 on 2022-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_booknow_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='static/pdfimage'),
        ),
    ]
