# Generated by Django 4.0 on 2022-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_booknow_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_pdf',
            field=models.FileField(null=True, upload_to='static/pdf'),
        ),
    ]
