# Generated by Django 4.0 on 2022-03-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_upload_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upload_pdf',
        ),
    ]
